# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        service: ['PingService', 'StatsService', 'SearchService']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.9'
    
    - name: Build and Test ${{ matrix.service }}
      working-directory: ${{ matrix.service }}
      run: |
        swift build --package-path ./
        swift test --package-path ./
